v1.7.1 (#2)
* improv!: remove link and unlink commands
- add uninstall script instead

* improv: rework how variables are passed to backend and template scripts

* chore: update version

diff --git a/install b/install
--- a/install
+++ b/install
@@ -4,4 +4,22 @@
 #
 destination="${1:-${HOME}/.local/bin}"
 
-PM_INSTALL_DIR="$(pwd)" ./pm link "${destination}"
+source="$(pwd)"
+
+if [[ -f "${destination}/pm" ]]; then
+    echo "there is already a link in ${destination}"
+    exit 1
+fi
+
+if [[ ! -d "${source}" ]]; then
+    echo "source directory ${source} does not exist"
+    exit 1
+fi
+
+if [[ ! -f "${source}/pm" ]]; then
+    echo "script 'pm' not found in ${source}"
+    exit 1
+fi
+
+command ln -s "${source}/pm" "${destination}/pm"
+echo "link created in ${destination}"
